settings:
  title: 'Status Page'
  url: 'https://status.wongm.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: wongm.com
    name: wongm.com
    url: 'https://wongm.com/'
    
  - id: railgallery.wongm.com
    name: Wongm's Rail Gallery
    url: 'https://railgallery.wongm.com/'
    
  - id: modelrail.wongm.com
    name: Marcus' Model Railways
    url: 'https://modelrail.wongm.com/'
    
  - id: raildocs.wongm.com
    name: Wongm's Rail Document Collection
    url: 'https://raildocs.wongm.com/'
    
  - id: tramdetective.wongm.com
    name: Tram Detective
    url: 'https://tramdetective.wongm.com/quality.php'
    
  - id: jakejunior.wongm.com
    name: Jake Junior
    url: 'https://jakejunior.wongm.com/'
    
  - id: tramfleet.wongm.com
    name: Melbourne's Tram Fleet
    url: 'https://tramfleet.wongm.com/'
    
  - id: zenphoto.wongm.com
    name: Zenphoto Example Gallery
    url: 'https://zenphoto.wongm.com/'
    
  - id: code.wongm.com
    name: Code Blog
    url: 'https://code.wongm.com/'
    
  - id: subscribe.wongm.com
    name: Supporters of Marcus Wong
    url: 'https://subscribe.wongm.com/'
    
  - id: railgeelong.com
    name: Rail Geelong
    url: 'https://www.    railgeelong.com/'
    
  - id: checkerboardhill.com
    name: Checkerboard Hill
    url: 'https://www.checkerboardhill.com/'
    
  - id: eurogunzel.com
    name: Euro Gunzel
    url: 'https://www.eurogunzel.com/'
    
  - id: vlinecars.com
    name: V/LineCars
    url: 'https://www.vlinecars.com/'
    
  - id: tracker.vlinecars.com
    name: V/LineCars Tracker
    url: 'https://tracker.vlinecars.com/'
    
  - id: vnsc.org.au
    name: Victorian N Scale Collective
    url: 'https://www.vnsc.org.au/'
